spring:
  profiles:
    active: local
  application:
    name: shallchic-spider
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    time-zone: GMT-0
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        enable_lazy_load_no_trans: true
    open-in-view: true
  web:
    resources:
      add-mappings: false
